name: Add review template

# **What it does**: When a specific label is added to a PR, adds the contents of .github/review-template.md as a comment in the PR
# **Why we have it**: To help reviewer know what to check for
# **Who does it impact**: maintainers and contributors

on:
  pull_request:
    types:
      - labeled

permissions:
    pull-requests: write
    contents: read

jobs:
  comment-that-approved:
    name: Add review template
    runs-on: self-hosted
    if: github.event.label.name == 'add review template'
    # && github.repository == 'github/docs-internal'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Jump through some hoops to work with a multi-line file
      - name: Store review template in variable
        run: |
          TEMPLATE=$(cat .github/review-template.md)
          echo "TEMPLATE<<EOF" >> $GITHUB_ENV
          echo "$TEMPLATE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on the PR and remove label
        run: |
          gh pr comment $PR --body "$TEMPLATE"
          gh pr edit $PR --remove-label 'add review template'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            #${{ secrets.PAT_WORKFLOW_CLASSIC }}
            #${{ secrets.DOCS_BOT_PAT_WORKFLOW_READORG }}
          PR: ${{ github.event.pull_request.html_url }}
          TEMPLATE: ${{ env.TEMPLATE }}
