name: No TODO or FIXME comments

# **What it does**: When a push is done we will test our checks against the code
# Checks can later be used to reject pull request for specific targets.
# **Why we have it**: To help reviewer know what to check for
# **Who does it impact**: maintainers and contributors

on:
  push:
#    paths:
#      - '**.h'
#      - '**.c'

permissions:
    pull-requests: write
    contents: read

jobs:
  check-code:
    name: Check code for developer comments that should not be in production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Check if source code contains either TODO or FIXME messages
      - name: Search for banned key words
        run: bash ./.github/scripts/contains-development-comments.sh
